// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ThroughTheAges.Bot.Context;

namespace ThroughTheAges.Bot.Migrations
{
    [DbContext(typeof(CardContext))]
    [Migration("20200721001508_extendedFields")]
    partial class extendedFields
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6");

            modelBuilder.Entity("ThroughTheAges.Bot.Models.Card", b =>
                {
                    b.Property<int>("CardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BlueTokens")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BuildCost")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BuildSteps")
                        .HasColumnType("TEXT");

                    b.Property<int>("BuildingLimit")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CivilActions")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Colonization")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CountFourPlayers")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CountThreePlayers")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CountTwoPlayers")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CultureProduction")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Discontent")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FoodProduction")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Happiness")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MilitaryActions")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("ResourceProduction")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RevolutionCost")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ScienceProduction")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StrengthProduction")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TechCost")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<int>("YellowTokens")
                        .HasColumnType("INTEGER");

                    b.HasKey("CardId");

                    b.ToTable("Cards");
                });
#pragma warning restore 612, 618
        }
    }
}
